spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/greendb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1208

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.sql=debug

spring.sql.init.mode = always

spring.sql.init.data-locations=classpath:/sql/data.sql
spring.jpa.defer-datasource-initialization=true

server.port=8080

# KOSIS API
api.kosis.key=NTc1ODRhODZhOTY4ZDdmNzNiMjFiMzZkMjAyNWViZTY=
api.kosis.base-url=https://kosis.kr/openapi/Param/statisticsParameterData.do
api.kosis.org-id=106
api.kosis.tbl-id=DT_106N_99_2800026

# 기상청 API
api.weather.key=07d617b99e65f217218cb522b551064355e286c26cf9053a25cf94086d1504be
api.weather.base-url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0

#사업자 진위 여부 api
nts.api.key=f71f7ecaaccba191039a493789616017dd996a320d9332a007b00227b622388a