spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/greendb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.sql=debug

spring.sql.init.mode = always

spring.sql.init.data-locations=classpath:/sql/data.sql
spring.jpa.defer-datasource-initialization=true

server.port=8080
